name: personal-blog-app

services:
  app:
    image: personal-blog-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER:
      MINIO_ROOT_PASSWORD:
    ports:
      - 9000:9000
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
